### ISSUE TITLE
Multiple Hetzner projects issue

### ISSUE THREAD

**Issue by rc5hack** [apricote/grafana-hcloud-datasource#6]
Hello and thank you for your time and patience!

- I have 6 projects in hetzner cloud
- I created 6 separate read-only API tokens (one for each project) in hetzner cloud
- I installed apricote-hcloud-datasource 0.2.0 to my grafana 10.3.3
- I added 6 data sources with 6 API tokens, self-test says "Successfully connected to Hetzner Cloud API"
- I imported [hetzner-cloud-servers-load-balancers dashboard](https://grafana.com/grafana/dashboards/20257-hetzner-cloud-servers-load-balancers/) to my grafana
  - When importing the dashboard, I have to choose one of 6 data sources (see image attached), I couldn't choose multiple of them or none of them, I forced to choose just one 
   ![image](https://github.com/apricote/grafana-hcloud-datasource/assets/1535521/b266706e-db90-48fd-b75e-a30a3d5844e9)
  - On the dashboard created, only servers from the data sources which was choosed on the previous step are available
  - No way to switch to servers from others data sources (hetzner projects), although other data sources (hetzner projects) are visible on "Project" picker on the dashboard

So my 6 project are all there, but I could view only servers from the project which was choosed while importing the dashboard and I couldn't switch between the projects on the fly.

How could I fix that?

**Comment by apricote** [comment]
Looks like the Dashboard Import overrides the datasources in every single query. I can reproduce this in all kinds of manual imports (Dashboard ID, JSON File, JSON Text). 

It works if you manually force the JSON to equal the published dashboard, ie. by editing the JSON Model after importing, or if you use the dashboard provisioner: https://grafana.com/tutorials/provision-dashboards-and-data-sources/#provision-a-dashboard

If you have any ideas how to fix this I am open to suggestions.

**Comment by rc5hack** [comment]
> by editing the JSON Model after importing

- Importing [hetzner-cloud-servers-load-balancers dashboard](https://grafana.com/grafana/dashboards/20257-hetzner-cloud-servers-load-balancers/)
- See the problem from 1st post
- Dashboard settings -> JSON Model -> select all -> delete all -> paste from [dashboard sources](https://grafana.com/grafana/dashboards/20257-hetzner-cloud-servers-load-balancers/) ("Download JSON") -> Save changes
- Dashboard breaks down completely: "no data" in every panel, empty "Servers" dropdown

![Dashboard](https://github.com/apricote/grafana-hcloud-datasource/assets/1535521/563f8482-15f2-4e6b-b618-ce76404fb81b)

**Comment by rc5hack** [comment]
dashboard edit changelog:

![changelog](https://github.com/apricote/grafana-hcloud-datasource/assets/1535521/9f57dddb-d36b-4664-aa12-56a28a794c50)

**Comment by rc5hack** [comment]
This update definitely solved my problem. Thank you! 🥳
