### ISSUE TITLE
Issue with consistency of order of results

### ISSUE THREAD

**Issue by jbheuschen** [apricote/grafana-hcloud-datasource#7]
Hi there, first of all, thanks for providing this great grafana plugin!

I'm not an expert on grafana, so please excuse me if I'm missing something obvious here right now.

I'm having difficulties with ensuring consistency of the results being returned by the data source. I.e., the order in which servers/load balancers are returned seems to be random (and thus is the color assigned by grafana), which makes it hard to read dashboards that regularly refresh.
I found a way to sort the columns of the results using the Organize transformation, but I don't think this is the best way, since it is kind of hardcoded.
The other sorting transformations provided by grafana don't seem to apply to this case. From what I read, this seems to be something that is usually done on the data source-side (e.g., by sorting within an Influx query).

The "phenomenon" can also be seen on the demo dashboard.

Therefore, my question is if this data source provides any way to ensure a consistent default order of results (for instance, sorted by server id) on the data source side.

Thanks in advance for your help!

**Comment by apricote** [comment]
Hey, thanks for the report! This was fixed by sorting the returned data by resource ID and series name.

I will publish a new version soon and submit for the Grafana marketplace.

**Comment by apricote** [comment]
Version 0.3.0 is now available from the marketplace: https://grafana.com/grafana/plugins/apricote-hcloud-datasource/?tab=changelog
